-- USE CoOperate;

-- Advisors
insert into Advisors (FirstName, LastName, College, Email) values ('Felita', 'Goulden', 'College of Science', 'fgoulden0@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('West', 'Basnall', 'Khoury College of Computer Science', 'wbasnall1@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Gale', 'Gianotti', 'College of Engineering', 'ggianotti2@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Jeff', 'Redhole', 'College of Science', 'jredhole3@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Maurine', 'Hammatt', 'Bouve College of Health Sciences', 'mhammatt4@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Veronike', 'Pembry', 'College of Engineering', 'vpembry5@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Evin', 'McFeate', 'College of Engineering', 'emcfeate6@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Hilly', 'Whorf', 'CAMD', 'hwhorf7@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Buck', 'Roads', 'Bouve College of Health Sciences', 'broads8@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Sumner', 'Demageard', 'Bouve College of Health Sciences', 'sdemageard9@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Terrell', 'Fabbri', 'College of Science', 'tfabbria@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Ernest', 'Priscott', 'Khoury College of Computer Science', 'epriscottb@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Leonard', 'Cowden', 'D''Amore-McKim School of Business', 'lcowdenc@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Fionnula', 'Chesnay', 'CAMD', 'fchesnayd@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Nobie', 'Genever', 'CAMD', 'ngenevere@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Mandy', 'Ajean', 'Bouve College of Health Sciences', 'majeanf@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Malachi', 'Strowther', 'D''Amore-McKim School of Business', 'mstrowtherg@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Christin', 'Kynge', 'Khoury College of Computer Science', 'ckyngeh@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Daryn', 'Gate', 'College of Science', 'dgatei@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Rosetta', 'Yeardsley', 'College of Science', 'ryeardsleyj@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Herschel', 'Jenkison', 'CAMD', 'hjenkisonk@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Wait', 'Cruess', 'College of Engineering', 'wcruessl@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Ralph', 'Yakovich', 'D''Amore-McKim School of Business', 'ryakovichm@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Graham', 'Flecknell', 'Khoury College of Computer Science', 'gflecknelln@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Norry', 'Wilprecht', 'Bouve College of Health Sciences', 'nwilprechto@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Teodoor', 'Brocklebank', 'D''Amore-McKim School of Business', 'tbrocklebankp@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Sabra', 'Vaggs', 'Bouve College of Health Sciences', 'svaggsq@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Beverlee', 'Mortell', 'College of Science', 'bmortellr@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Horatius', 'Botten', 'CAMD', 'hbottens@northeastern.edu');
insert into Advisors (FirstName, LastName, College, Email) values ('Herta', 'Kennady', 'CAMD', 'hkennadyt@northeastern.edu');


-- Students
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Freddi', 'Garroch', 3.46, 'Engineering@northeastern.edu', 5, 'Khoury College of Computer Science', 19, 'fgarroch0@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Michaelina', 'Klugman', 3.31, 'Business Administration@northeastern.edu', 6, 'Khoury College of Computer Science', 3, 'mklugman1@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Lorrie', 'Isakov', 3.54, 'Psychology@northeastern.edu', 6, 'Bouve College of Health Sciences', 24, 'lisakov2@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Hannah', 'Crabtree', 2.62, 'Communications@northeastern.edu', 4, 'CAMD', 15, 'hcrabtree3@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Kathlin', 'Legister', 3.81, 'Psychology@northeastern.edu', 2, 'College of Science', 4, 'klegister4@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Janis', 'Veeler', 2.35, 'Mathematics@northeastern.edu', 4, 'CAMD', 27, 'jveeler5@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Bili', 'Chisholme', 3.17, 'History@northeastern.edu', 2, 'Bouve College of Health Sciences', 19, 'bchisholme6@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Darrin', 'Apark', 2.79, 'Business Administration@northeastern.edu', 6, 'College of Engineering', 19, 'dapark7@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Trisha', 'Berling', 2.35, 'Psychology@northeastern.edu', 5, 'Bouve College of Health Sciences', 17, 'tberling8@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Wald', 'Grayland', 2.21, 'Sociology@northeastern.edu', 3, 'College of Engineering', 29, 'wgrayland9@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Gabriella', 'Commin', 3.81, 'Psychology@northeastern.edu', 3, 'College of Science', 7, 'gcommina@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Cordey', 'Madge', 2.39, 'Psychology@northeastern.edu', 1, 'College of Science', 22, 'cmadgeb@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Yurik', 'Friedlos', 3.54, 'English Literature@northeastern.edu', 1, 'Khoury College of Computer Science', 26, 'yfriedlosc@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Kimmie', 'Rumming', 3.02, 'Biology@northeastern.edu', 6, 'CAMD', 3, 'krummingd@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Angelita', 'Tolworth', 2.01, 'History@northeastern.edu', 3, 'Khoury College of Computer Science', 29, 'atolworthe@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Iris', 'Wiggett', 3.18, 'Sociology@northeastern.edu', 2, 'College of Engineering', 27, 'iwiggettf@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Faye', 'Assiter', 3.08, 'Biology@northeastern.edu', 4, 'Khoury College of Computer Science', 29, 'fassiterg@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Franky', 'Loudyan', 2.51, 'Computer Science@northeastern.edu', 3, 'CAMD', 6, 'floudyanh@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Evania', 'Filipson', 3.68, 'Communications@northeastern.edu', 3, 'Bouve College of Health Sciences', 2, 'efilipsoni@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Redd', 'Donati', 2.16, 'Biology@northeastern.edu', 3, 'Bouve College of Health Sciences', 28, 'rdonatij@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Wilma', 'Dowyer', 3.73, 'English Literature@northeastern.edu', 4, 'Bouve College of Health Sciences', 7, 'wdowyerk@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Tricia', 'Piggot', 2.79, 'History@northeastern.edu', 5, 'College of Science', 11, 'tpiggotl@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Andreana', 'Brusin', 2.53, 'Computer Science@northeastern.edu', 1, 'Khoury College of Computer Science', 21, 'abrusinm@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Melony', 'Esposi', 3.09, 'Biology@northeastern.edu', 5, 'D''Amore-McKim School of Business', 8, 'mesposin@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Catharine', 'Fishpoole', 2.54, 'Psychology@northeastern.edu', 6, 'Bouve College of Health Sciences', 9, 'cfishpooleo@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Jaquenette', 'Andersch', 2.89, 'Psychology@northeastern.edu', 4, 'Bouve College of Health Sciences', 8, 'janderschp@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Lydia', 'Baudinot', 3.67, 'Communications@northeastern.edu', 5, 'College of Engineering', 13, 'lbaudinotq@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Dasha', 'Crossdale', 2.06, 'Business Administration@northeastern.edu', 1, 'Bouve College of Health Sciences', 19, 'dcrossdaler@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Ashil', 'Lydiate', 2.22, 'Mathematics@northeastern.edu', 6, 'Bouve College of Health Sciences', 2, 'alydiates@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Ceil', 'Monro', 3.45, 'Business Administration@northeastern.edu', 2, 'CAMD', 17, 'cmonrot@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Randolph', 'Capewell', 3.1, 'Mathematics@northeastern.edu', 4, 'CAMD', 3, 'rcapewellu@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Callida', 'Ollin', 2.85, 'Business Administration@northeastern.edu', 4, 'D''Amore-McKim School of Business', 26, 'collinv@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Welsh', 'Dalyiel', 3.45, 'English Literature@northeastern.edu', 6, 'Khoury College of Computer Science', 6, 'wdalyielw@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Sherill', 'Ladloe', 3.73, 'Biology@northeastern.edu', 3, 'College of Science', 7, 'sladloex@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Massimiliano', 'Castelletto', 2.16, 'Psychology@northeastern.edu', 2, 'Khoury College of Computer Science', 15, 'mcastellettoy@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Jemmy', 'Stanier', 3.79, 'English Literature@northeastern.edu', 5, 'College of Engineering', 15, 'jstanierz@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Diane', 'Brookton', 3.37, 'Communications@northeastern.edu', 2, 'College of Engineering', 16, 'dbrookton10@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Walden', 'Hairsine', 2.75, 'Engineering@northeastern.edu', 2, 'Bouve College of Health Sciences', 28, 'whairsine11@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Antone', 'Trynor', 3.83, 'Engineering@northeastern.edu', 1, 'CAMD', 25, 'atrynor12@northeastern.edu');
insert into Students (FirstName, LastName, GPA, Major, CurrentYear, HomeCollege, AdvisorID, Email) values ('Anne', 'Wellbank', 3.73, 'Business Administration@northeastern.edu', 6, 'Khoury College of Computer Science', 27, 'awellbank13@northeastern.edu');
